#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting livecd setup"
    for x in $(cat /proc/cmdline)
        do
        case ${x} in
                xfce) /usr/bin/detect-opengl.sh && /etc/init.d/gdm start
                ;;
                xkeymap=*) export ${x} && cp /usr/share/hal/fdi/policy/10osvendor/10-keymap.fdi /etc/hal/fdi/policy/ && sed -i "s|>us<|>$keymap<|" /etc/hal/fdi/policy/10-keymap.fdi
                ;;
                keymap=*) export ${x} && loadkeys $keymap
                ;;
        esac
    done
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon livecd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping livecd setup"
    /bin/true
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon livecd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
